### PR TITLE
ZeroFrame Wrapper Fixes

### PR DESCRIPTION
**Pull request by anoadragon453**
Many fixes to the ZeroFrame API page, with more to come soon.

Cleaned up wording, moved examples into collapsable sections, added CoffeeScript and JavaScript examples with output and checked they all worked.

To accomplish this, one more dependency was added for some mkdocs addons, but [they're very nice](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) and I encourage us to make use of them where beneficial!

### CODE REVIEW

**Comment by blurHY** [comment]
Yeah,code should be surrounded with backticks.

`"string"`

**Comment by anoadragon453** [comment]
@blurHY Which line(s) are you referring to?

**Comment by blurHY** [comment]
No,I just said the `ok` should be `"ok"`

**Comment by anoadragon453** [comment]
Okie.

@HelloZeroNet review please? :)

**Comment by HelloZeroNet** [comment]
Can you please resolve the conflicting files?

**Comment by anoadragon453** [comment]
Oh, derp sorry, mobile view doesn't show them.

**Comment by anoadragon453** [comment]
Fixed!

**Comment by HelloZeroNet** [comment]
Thanks, merged, looking great: https://zeronet.io/docs/site_development/zeroframe_api_reference 

The only missing piece is the logo and probably we could make the example Js by default, but it's also good this way

**Pull request merged**
