### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by blurHY**

### CODE REVIEW

**Comment by rllola** [comment]
You also need to modify the dropdown menu to add chinese : https://github.com/blurHY/Documentation/blob/master/docs/resources/partials/header.html#L65

**Comment by blurHY** [comment]
OK.Item added.
I noticed that mkdocs's search plugin doesn't support Chinese.

**Comment by rllola** [comment]
> OK.Item added.
> I noticed that mkdocs's search plugin doesn't support Chinese.

No unfortunately it doesn't.

**Comment by anoadragon453** [comment]
Japanese is supported though. Perhaps some minor tweaks can be made to the [code for Japanese search](https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.ja.js) to support Chinese?

**Pull request merged**
