### PR TITLE
Switch to mkdocs-material theme

### PR DESCRIPTION
**Pull request by anoadragon453**
See a demo here: https://zerodocs.amorgan.xyz/

Much nicer than the readthedocs theme IMO.

Edit: Ok, happy with how it looks now.

### CODE REVIEW

**Comment by krixano** [comment]
ooooooh

**Comment by anoadragon453** [comment]
@HelloZeroNet Any status update on this?

**Comment by HelloZeroNet** [comment]
Yeah, Thanks for the PR. I wasn't able to decide if I like the new or the old design better, but now after a second look I prefer the new one. The only thing we have to fix is currently missing the list of API calls.

**Comment by anoadragon453** [comment]
Thanks for the response! Can you point me to exactly what you mean? Not the [ZeroFrame API Reference](https://zerodocs.amorgan.xyz/site_development/zeroframe_api_reference/), right?

**Comment by HelloZeroNet** [comment]
Yes, that one, ZeroFrame API Reference missing the "Table of contents" from the right side

**Comment by anoadragon453** [comment]
Ahh, ok! Let me investigate why that isn't there.

**Comment by anoadragon453** [comment]
Ok, should be good!

**Comment by anoadragon453** [comment]
Noticed that some other pages could use a Table of Contents. I think I'm happy with this now.

**Comment by anoadragon453** [comment]
Does this look good to you now @HelloZeroNet?

**Comment by HelloZeroNet** [comment]
Yes, thanks again, let's see how well is it works on https://zeronet.readthedocs.io/ :)

**Comment by anoadragon453** [comment]
Ready to start fixing if anything breaks!

**Comment by anoadragon453** [comment]
@HelloZeroNet Any reason why the theme still isn't live?

**Comment by HelloZeroNet** [comment]
Hmm good question, maybe it's not supported by the readthedocs at all?

**Pull request merged**
